In [61]:
import pandas as pd
import tensorflow as tf

In [62]:
from tensorflow.keras.models import load_model
import numpy as np
import pickle

In [63]:
# load model
model = load_model('model.h5')

# load encoder and scaller

with open ('label_encoder_gender.pkl','rb') as file:
    labelabel_encoder_gender = pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [64]:
input_data={
    'CreditScore':600,
    'Geography':"France",
    'Gender':"Male",
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000,
}

In [65]:
with open('one_hot_encoder.pkl','rb') as file:
    one_hot_encoder = pickle.load(file)

In [66]:
encoded_geo = one_hot_encoder.transform([[input_data['Geography']]]).toarray()

/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [67]:
geo_encoded_df = pd.DataFrame(encoded_geo,columns=one_hot_encoder.get_feature_names_out())
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [68]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [69]:
input_df['Gender']= labelabel_encoder_gender.transform([input_df['Gender']])

/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [70]:
final_input_df = pd.concat([input_df.drop(['Geography'],axis=1),geo_encoded_df],axis=1)

In [71]:
scaled = scaler.transform(final_input_df)
scaled

array([[-0.47154541,  0.90911166,  0.09477172, -0.69844549, -0.29010416,
         0.80510537,  0.63367318,  0.95214374, -0.84805047,  0.98019606,
        -0.57581067, -0.56349184]])

In [72]:
# predict
prediction = model.predict(scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

In [74]:
prediction_prob = prediction[0][0]
prediction_prob

np.float32(0.023557315)

In [75]:
if prediction_prob >0.5 :
    print("customer is likely to churn")
else :
    print("Customer will not churn")

Customer will not churn